### PR TITLE
README enhancements

### PR DESCRIPTION
**Pull request by jjmaestro**
Just fixing two header tags with the incorrect indentation level (also practising GitHub branching and branch pull request :)

### CODE REVIEW

**Comment by maraujop** [comment]
Just let me know why are you still doing pull requests when you are a collaborator of the project :D

**Comment by jjmaestro** [comment]
I didn't realize I could pull into the maraujop repo 8)  In any case, it's good to practise the pull request procedure in GitHub XD

**Comment by maraujop** [comment]
Of course you can pull, anyone can :D hahaha, no problem, I can still be your favorite committer my friend.

**Comment by jjmaestro** [comment]
I meant push, of course 8)

**Pull request closed without merging**
