### PR TITLE
Missing MANIFEST.in breaks installation

### PR DESCRIPTION
**Pull request by chrisglass**
Since setup.py reads from README.textile, you need to include it in the egg. I added the license file too, for good mesure.

Cheers

### CODE REVIEW

**Comment by maraujop** [comment]
Thanks for the fix!

I honestly rarely install my apps as eggs, that's why I hadn't noticed this before.

**Comment by chrisglass** [comment]
Would be awesome if you could push a new version to pypi, that would save us a lot of trouble.

Keep up the good work :P Thanks a lot

**Comment by maraujop** [comment]
You are totally right,

I will do it today, as soon as I can. I always forget about pypi :) Thanks

**Comment by maraujop** [comment]
I just updated the package. I should have changed version and updated it as a new one, but it doesn't really matter.

**Pull request merged**
