### PR TITLE
Nonexistent perms shouldnt raise

### PR DESCRIPTION
**Pull request by chrisglass**
Hi,

Nonexistent shouldn't raise but return False.

Raising basically requires programmers to surround every has_perm call with a try/except block - that's not acceptable in complex projects.
This fixes the issue (and changes tests accordingly).

### CODE REVIEW

**Comment by maraujop** [comment]
Hi @chrisglass,

I understand what you say. When I programmed this I thought that I would like the backend to warn me I was checking a non existent rule. You don't need to surround every `has_perm` call with a try/except if the rules you check exist. 

I know that in big projects things change, and it's hard to control all the rules. But many people will find themselves lost if a rule always returns False and they think it exists, imagine a small typo. That part of your functionality will not work, as no user has rights to do it. So the user tries to do something he knows he can do and nothing happens, don't you think is better to show a custom 500 saying: "ey! we know something went wrong, we will fix it right away"

Security is the main concern of this backend, and checking rules that don't exist, is one of those things I prefer to know. Can you try to elaborate a little bit more? See if you can convince me on this. Maybe we can log the error or something like that.

Thanks, regards
Miguel

**Comment by jjmaestro** [comment]
Hi Chris!

I completely back up maraujop's opinion about django-rules being a security-minded app. On top of that, I firmly believe that this time (and in many others) raising an exception is the way to go (IMHO) because
- it is very explicit and clear about a _huge_ mistake: the rule that tries to enforce security fails but must fail soundly and not quietly
- Exceptions are exceptional :) A missing rule is not something your application can live without. So the 500 would be the best end result to show the user while you hotfix the problem immediately.

Finally, on a more personal note slightly related with your fix, lately I have personally started to avoid dealing with "magic returns" (NULL, -1, sometimes a boolean, etc) to deal with certain problems in the execution of my applications and I have favoured Exceptions. With Exceptions you can do Exception chaining, you can provide a clear message of what's going on, you explicitly code the "getting out of the error" clearly as opposed to dealing with a "magic value" within the normal flow of the method, etc.

I know it is a very fine line to walk, so I understand the different views on the matter. However, I rather err on the Exception side (especially this time).

Cheers,

## 

J. Javier Maestro

**Comment by chrisglass** [comment]
Well that means you are now inconsistent with other Django backends upon which users might want to fallback.
If you use permissions that are not defined in Django rules but in another backend (which is a perfectly valid use case), your raising an exception makes Django's fallback mechanism fail.

If you really want to know which rules exist or not, you should probably if DEBUG: raise else: return False...

I was suggesting to be consistent with the default Django backends...

**Comment by jjmaestro** [comment]
Oh! OK, that is something that I think we have not considered. But in any case, is it really that common to use multiple authorization backends? :-?

In my idea of an authorization backend, the moment you pass through one and fails, the execution should stop. I did not consider cascading down as an option, because I understand that an authorization backend should be the "Single Point of Failure" after a non-authorized access.

Can you elaborate more on the "inconsistent" behaviour? Perhaps you could show us your specific usage as an example of what you need and what you expect as "consistent Django behaviour".

Thanks a lot!

## 

J. Javier Maestro

**Comment by maraujop** [comment]
I hadn't thought on that either, 

I'm not using several authentication backends, as django-rules provides me with enough power, but I can picture a use case in which what you say is right. 

It looks like probably a intermediate solution will be the best. Don't take this personal, we just want to discuss the issue before rushing. 

I'm not very prone to add settings variables to apps, but the best approach here might be adding a variable like `PARANOID_MODE`, which if set to True, raises an exception and defaults to False. I rather raise a 500 in production, than confusing the user with not being able to take an action.

Thanks! 
Miguel

**Comment by jjmaestro** [comment]
I still can't really see the use case for multiple authentication backends... django-rules provides 101% of the stuff you would need, so why bother with something else? :) And if you need to maintain a legacy authentication backend while transitioning to django-rules, then you can patch your django-rules temporarily :D

Anyways, I could agree on a configuration constant... still rather ugly / weak at that level IMHO (again, I think that this code should be small, tiny and tidy) but I can understand the need in some corner cases. So, perhaps as maraujop suggests, a FALLBACK_MODE or PASSTHROUGH_MODE constant, that if not set or set to false should raise the Exception and if set, return false and move along.

However, I would still like to see some use case where this is needed, so if chrisglass is kind enough to provide some examples, it would be awesome :)

Thanks guys!

**Comment by chrisglass** [comment]
Well Django iterates through backends until either one returns True or the end of the list is reached: See https://github.com/django/django/blob/master/django/contrib/auth/models.py#L171

I would say it is the default behavior because precisely it's the most common usecase (LDAP integration, external auth provider...) :)

It's alright, we'll just fork. Hope we can still contribute something useful :) Feel free to close this as you see fit.

**Comment by jjmaestro** [comment]
Thanks for the link!

From what you say and what you link, I would then agree to follow your suggestion of changing the normal behaviour and perhaps leave a DEBUG flag to throw an exception during development or in pre-production. It still "hurts" a little, though, because to me, not having a rule is a "misconfiguration" more than a "not found, move along" case. But I guess being compatible is more important in this case :)

Let's hear maraujop! :D

Cheers!

**Comment by maraujop** [comment]
@chrisglass I'm aware of how Django works, I know the auth app in depth. When you explained the problem of chaining backends, I understood the necessity of being compatible, so people can use several at a time. 

As it appears that you are in a use case in which you need this feature. What do you think it would be the best way to proceed? Options are:
- Use `settings.DEBUG` to raise an Exception in case it's set.
- Add a variable that lets the user toggle the exception mechanism. Having it turned off by default. 

There's no need to fork, I understand this needs to be patched. Unless the feature requested or the changes are against the common sense principles that are behind django-rules, your code and improvements will be always welcome.

Thanks, regards
Miguel

**Comment by andornaut** [comment]
IMO, django-rules should be compatible with django's backend cascading. It is perfectly valid to expect django-rules to return False on a permission miss and let django cascade to the next backend in line. Raising an exception in DEBUG breaks compatibility just the same - an exception should not be raised for an unexceptional and valid use case.

**Comment by maraujop** [comment]
@andornaut

Totally agree with you. I just pushed @chrisglass pull request to master. I'm closing this.

**Pull request closed without merging**
